id = input('digite algo: ')
print('o tipo primito é: ', type(id))
print('é um número? ', id.isnumeric())
print('é alfabético? ', id.isalpha()) 
print('é alfanumérico? ', id.isalnum())
print('é maiúsculo? ', id.isupper())
print('é minúsculo? ', id.islower())
print('é capitalizado? ', id.istitle())
print('é um espaço? ', id.isspace())